<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Services\" />
    <Folder Include="Behaviors\" />
    <Folder Include="Common\Exceptions\" />
    <Folder Include="Common\Mapping\" />
    <Folder Include="Customers\" />
    <Folder Include="Cart\" />
    <Folder Include="Orders\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BikeShop.Domain\BikeShop.Domain.csproj" />
  </ItemGroup>

</Project>
